project_id = "pfhrbcvhjumqvjcxbose"

[functions.generate-batch-zip]
verify_jwt = true

[functions.extract-letter]
verify_jwt = true

[functions.invite-team-member]
verify_jwt = true

[functions.accept-team-invitation]
verify_jwt = true

[functions.manage-team-member]
verify_jwt = true